version: '3.8'
services:
  jscad:
    build: 
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
       - ../workspace/projects:/workspace/openjscad/packages/web/examples/:cached
       - ./devserver.js:/workspace/openjscad/packages/web/devserver.js:cached
    ports:
      - "3000:3000"
      - "8081:8081"
    user: node
  